name: CI
on:
  push:
    branches:
      - "**"

env:
  EM_VERSION: 3.1.42
  EM_CACHE_FOLDER: "emsdk-cache"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - run: pnpm install --frozen-lockfile
      # - run: pnpm run lint && pnpm run build && pnpm run test
      - run: pnpm run build && pnpm run test
